// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSitSodg2WrcDi94jR7hWfKBjOk7lj6to',
    appId: '1:341521927870:android:47a52685935ebd9573d8ef',
    messagingSenderId: '341521927870',
    projectId: 'spotbud-b9d9e',
    storageBucket: 'spotbud-b9d9e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKbvi7UfX8DTFZ2c7FzdhFYbJe2l_V5g',
    appId: '1:341521927870:web:a06db78d2e7ebf3673d8ef',
    messagingSenderId: '341521927870',
    projectId: 'spotbud-b9d9e',
    authDomain: 'spotbud-b9d9e.firebaseapp.com',
    storageBucket: 'spotbud-b9d9e.appspot.com',
    measurementId: 'G-3H2VF6LL7S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0t0lsj8wqA0cWXtJQ-PEvl4n4OzMXPDE',
    appId: '1:341521927870:ios:b1b753acb9c9344e73d8ef',
    messagingSenderId: '341521927870',
    projectId: 'spotbud-b9d9e',
    storageBucket: 'spotbud-b9d9e.appspot.com',
    androidClientId: '341521927870-2c3vffbkq8s346003ii0paghoi4agkl4.apps.googleusercontent.com',
    iosClientId: '341521927870-q6b6gm3et29hm22vaimm0a35rtariou7.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotbud',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0t0lsj8wqA0cWXtJQ-PEvl4n4OzMXPDE',
    appId: '1:341521927870:ios:3ab32127fe913fc073d8ef',
    messagingSenderId: '341521927870',
    projectId: 'spotbud-b9d9e',
    storageBucket: 'spotbud-b9d9e.appspot.com',
    androidClientId: '341521927870-2c3vffbkq8s346003ii0paghoi4agkl4.apps.googleusercontent.com',
    iosClientId: '341521927870-17f2qhni8c15ql8vsbfpu00rejut0ku8.apps.googleusercontent.com',
    iosBundleId: 'com.ram.spotbud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKKbvi7UfX8DTFZ2c7FzdhFYbJe2l_V5g',
    appId: '1:341521927870:web:dff15427efb19ffd73d8ef',
    messagingSenderId: '341521927870',
    projectId: 'spotbud-b9d9e',
    authDomain: 'spotbud-b9d9e.firebaseapp.com',
    storageBucket: 'spotbud-b9d9e.appspot.com',
    measurementId: 'G-5C442CD3Y4',
  );

}